# hpa.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tween-web-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tween-web-app
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

